"""Loop repository public surface.

Purpose:
    Re-export the feature-owned loop persistence modules behind one canonical
    `cloop.loops.repo` import surface.

Responsibilities:
    - Present one stable repository namespace to services, routes, CLI, MCP, and tests
    - Group focused persistence implementations into feature-owned submodules
    - Keep repository helpers discoverable without a monolithic implementation file

Non-scope:
    - Implementing SQL statements directly in this module
    - Business-rule validation above repository concerns
    - Transport-specific orchestration or response shaping
"""

from __future__ import annotations

from ._repo.claims import (
    claim_loop,
    list_active_claims,
    purge_expired_claims,
    read_claim,
    release_claim,
    release_claim_by_loop_id,
    renew_claim,
)
from ._repo.comments import (
    _row_to_comment,
    count_comments,
    create_comment,
    get_comment,
    list_comments,
    soft_delete_comment,
    update_comment,
)
from ._repo.core import (
    create_loop,
    delete_loop,
    export_loops_filtered,
    find_loop_by_raw_text,
    find_loop_by_title,
    insert_loop_from_export,
    list_all_loops,
    list_loops,
    list_loops_by_statuses,
    list_loops_by_tag,
    list_next_loop_candidates,
    list_tags,
    read_loop,
    read_loops_batch,
    search_loops,
    update_loop_fields,
)
from ._repo.dependencies import (
    add_dependency,
    detect_dependency_cycle,
    has_open_dependencies,
    has_open_dependencies_batch,
    list_children,
    list_dependencies,
    list_dependents,
    list_open_dependencies,
    remove_dependency,
)
from ._repo.embeddings import (
    fetch_loop_embeddings,
    read_loop_embeddings_batch,
    upsert_loop_embedding,
)
from ._repo.events import (
    answer_loop_clarification,
    get_latest_reversible_event,
    insert_loop_clarification,
    insert_loop_event,
    insert_loop_suggestion,
    list_answered_clarifications,
    list_loop_clarifications,
    list_loop_clarifications_for_loops,
    list_loop_events,
    list_loop_events_paginated,
    list_loop_suggestions,
    list_pending_suggestions,
    list_pending_suggestions_for_loops,
    list_unanswered_clarification_questions,
    list_unanswered_clarifications_for_loops,
    read_loop_clarification,
    read_loop_suggestion,
    resolve_loop_suggestion,
)
from ._repo.metadata import (
    _upsert_tags_batch,
    list_loop_tags,
    list_loop_tags_batch,
    list_projects,
    read_project_name,
    read_project_names_batch,
    replace_loop_tags,
    upsert_project,
    upsert_tag,
)
from ._repo.nudges import (
    get_nudge_state,
    get_nudge_states_batch,
    reset_nudge_state,
    upsert_nudge_state,
)
from ._repo.planning_sessions import (
    create_planning_session,
    create_planning_session_run,
    delete_planning_session,
    delete_planning_session_runs,
    get_planning_session,
    get_planning_session_run,
    list_planning_session_runs,
    list_planning_sessions,
    update_planning_session,
    update_planning_session_run,
)
from ._repo.relationships import (
    insert_loop_link,
    list_loop_links_by_type,
    list_loop_links_for_loop_ids,
    upsert_loop_link,
)
from ._repo.review_sessions import (
    create_review_action_preset,
    create_review_session,
    delete_review_action_preset,
    delete_review_session,
    get_review_action_preset,
    get_review_session,
    list_review_action_presets,
    list_review_sessions,
    update_review_action_preset,
    update_review_session,
)
from ._repo.shared import _row_to_record
from ._repo.templates import (
    create_loop_template,
    delete_loop_template,
    get_loop_template,
    get_loop_template_by_name,
    list_loop_templates,
    update_loop_template,
)
from ._repo.timers import (
    _row_to_time_session,
    count_time_sessions,
    create_time_session,
    delete_time_session,
    get_active_time_session,
    get_total_tracked_time,
    list_time_sessions,
    stop_time_session,
)
from ._repo.views import (
    _cursor_where_clause,
    create_loop_view,
    delete_loop_view,
    get_loop_view,
    get_loop_view_by_name,
    list_loop_views,
    list_loops_cursor,
    search_loops_by_query,
    search_loops_by_query_cursor,
    update_loop_view,
)
from ._repo.working_sets import (
    create_working_set,
    create_working_set_item,
    delete_working_set,
    delete_working_set_item,
    get_working_set,
    get_working_set_context,
    get_working_set_item,
    list_working_set_items,
    list_working_sets,
    reorder_working_set_items,
    update_working_set,
    update_working_set_context,
    update_working_set_item,
)

__all__ = [
    "_row_to_record",
    "create_loop",
    "read_loop",
    "delete_loop",
    "list_loops",
    "list_loops_by_statuses",
    "list_next_loop_candidates",
    "list_all_loops",
    "export_loops_filtered",
    "find_loop_by_raw_text",
    "find_loop_by_title",
    "list_loops_by_tag",
    "insert_loop_from_export",
    "list_tags",
    "search_loops",
    "update_loop_fields",
    "read_loops_batch",
    "insert_loop_event",
    "list_loop_events",
    "list_loop_events_paginated",
    "get_latest_reversible_event",
    "insert_loop_suggestion",
    "read_loop_suggestion",
    "list_loop_suggestions",
    "list_pending_suggestions",
    "list_pending_suggestions_for_loops",
    "resolve_loop_suggestion",
    "insert_loop_clarification",
    "read_loop_clarification",
    "list_loop_clarifications",
    "list_loop_clarifications_for_loops",
    "list_unanswered_clarifications_for_loops",
    "answer_loop_clarification",
    "list_answered_clarifications",
    "list_unanswered_clarification_questions",
    "upsert_project",
    "read_project_name",
    "read_project_names_batch",
    "list_loop_tags_batch",
    "list_projects",
    "upsert_tag",
    "list_loop_tags",
    "_upsert_tags_batch",
    "replace_loop_tags",
    "insert_loop_link",
    "upsert_loop_link",
    "list_loop_links_by_type",
    "list_loop_links_for_loop_ids",
    "read_loop_embeddings_batch",
    "fetch_loop_embeddings",
    "upsert_loop_embedding",
    "search_loops_by_query",
    "create_loop_view",
    "list_loop_views",
    "get_loop_view",
    "get_loop_view_by_name",
    "update_loop_view",
    "delete_loop_view",
    "_cursor_where_clause",
    "list_loops_cursor",
    "search_loops_by_query_cursor",
    "create_working_set",
    "list_working_sets",
    "get_working_set",
    "update_working_set",
    "delete_working_set",
    "list_working_set_items",
    "get_working_set_item",
    "create_working_set_item",
    "update_working_set_item",
    "delete_working_set_item",
    "reorder_working_set_items",
    "get_working_set_context",
    "update_working_set_context",
    "claim_loop",
    "read_claim",
    "renew_claim",
    "release_claim",
    "release_claim_by_loop_id",
    "purge_expired_claims",
    "list_active_claims",
    "add_dependency",
    "remove_dependency",
    "list_dependencies",
    "list_dependents",
    "list_open_dependencies",
    "has_open_dependencies",
    "has_open_dependencies_batch",
    "detect_dependency_cycle",
    "list_children",
    "_row_to_time_session",
    "create_time_session",
    "get_active_time_session",
    "stop_time_session",
    "list_time_sessions",
    "count_time_sessions",
    "get_total_tracked_time",
    "delete_time_session",
    "create_loop_template",
    "list_loop_templates",
    "get_loop_template",
    "get_loop_template_by_name",
    "update_loop_template",
    "delete_loop_template",
    "_row_to_comment",
    "create_comment",
    "list_comments",
    "get_comment",
    "update_comment",
    "soft_delete_comment",
    "count_comments",
    "get_nudge_state",
    "upsert_nudge_state",
    "reset_nudge_state",
    "get_nudge_states_batch",
    "create_review_action_preset",
    "list_review_action_presets",
    "get_review_action_preset",
    "update_review_action_preset",
    "delete_review_action_preset",
    "create_review_session",
    "list_review_sessions",
    "get_review_session",
    "update_review_session",
    "delete_review_session",
    "create_planning_session",
    "list_planning_sessions",
    "get_planning_session",
    "update_planning_session",
    "delete_planning_session",
    "create_planning_session_run",
    "get_planning_session_run",
    "update_planning_session_run",
    "list_planning_session_runs",
    "delete_planning_session_runs",
]
