"""Static file serving for the Vite-built Cloop web frontend.

Purpose:
    Serve the production frontend bundle generated by the dedicated Vite +
    TypeScript workspace.

Responsibilities:
    - Serve the SPA HTML entrypoint at `/`.
    - Serve root-level PWA assets (`/manifest.json`, `/favicon.ico`, `/sw.js`).
    - Apply cache-control headers appropriate for hashed bundle assets and mutable
      root entry files.
    - Fail loudly with actionable guidance when the frontend build is missing.

Scope:
    - Static frontend asset serving only.

Non-scope:
    - API endpoint behavior and business orchestration.
    - Frontend build execution itself (handled by the Vite workspace).

Usage:
    - Imported by `cloop.main` to mount `/static` and include the root web router.
    - Built assets are emitted to `src/cloop/static/dist` by `pnpm --dir frontend build`.

Invariants/Assumptions:
    - Production app assets live under `src/cloop/static/dist`.
    - Hashed bundle assets are emitted under `/static/assets/*`.
    - Root PWA assets are emitted at the dist root and served explicitly here.
"""

from __future__ import annotations

import re
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, HTMLResponse, Response
from fastapi.staticfiles import StaticFiles

_STATIC_DIR = Path(__file__).resolve().parent / "static"
FRONTEND_DIST_DIR = _STATIC_DIR / "dist"
_HASHED_ASSET_RE = re.compile(r".+-[A-Za-z0-9_-]{8,}\.(?:css|js|mjs|svg|png|jpe?g|gif|woff2?)$")

router = APIRouter()


def _require_file(path: Path, logical_name: str) -> Path:
    if path.exists():
        return path
    raise HTTPException(
        status_code=503,
        detail=(
            f"Frontend build missing: {logical_name}. "
            "Run `pnpm --dir frontend build` before serving the web UI."
        ),
    )


def _dist_file_response(
    filename: str,
    *,
    media_type: str,
    cache_control: str,
    extra_headers: dict[str, str] | None = None,
) -> FileResponse:
    """Serve a root-level built frontend asset with explicit cache headers."""
    file_path = _require_file(FRONTEND_DIST_DIR / filename, filename)
    headers = {"Cache-Control": cache_control}
    if extra_headers:
        headers.update(extra_headers)
    return FileResponse(file_path, media_type=media_type, headers=headers)


class CloopStaticFiles(StaticFiles):
    """Static file server with Vite-aware cache behavior for built assets."""

    def file_response(self, *args, **kwargs) -> Response:
        response = super().file_response(*args, **kwargs)
        full_path_arg = args[0] if args else kwargs.get("full_path")
        full_path = Path(full_path_arg) if full_path_arg is not None else None
        if full_path is None:
            return response

        if "assets" in full_path.parts and _HASHED_ASSET_RE.fullmatch(full_path.name):
            response.headers["Cache-Control"] = "public, max-age=31536000, immutable"
            return response

        if full_path.suffix in {".js", ".css", ".html", ".map"}:
            response.headers["Cache-Control"] = "no-cache"
        elif full_path.suffix in {".png", ".jpg", ".jpeg", ".svg", ".ico", ".webp"}:
            response.headers["Cache-Control"] = "public, max-age=86400"

        return response


@router.get("/", response_class=HTMLResponse)
def serve_index() -> HTMLResponse:
    """Serve the built SPA HTML entrypoint."""
    index_path = _require_file(FRONTEND_DIST_DIR / "index.html", "index.html")
    html = index_path.read_text(encoding="utf-8")
    return HTMLResponse(html, headers={"Cache-Control": "no-cache"})


@router.get("/manifest.json")
def serve_manifest() -> FileResponse:
    """Serve the web app manifest with correct content type."""
    return _dist_file_response(
        "manifest.json",
        media_type="application/manifest+json",
        cache_control="public, max-age=86400",
    )


@router.api_route("/favicon.ico", methods=["GET", "HEAD"], include_in_schema=False)
def serve_favicon() -> FileResponse:
    """Serve the browser favicon from the canonical root path."""
    return _dist_file_response(
        "favicon.ico",
        media_type="image/x-icon",
        cache_control="public, max-age=86400",
    )


@router.get("/sw.js")
def serve_service_worker() -> FileResponse:
    """Serve the service worker with registration-safe cache headers."""
    return _dist_file_response(
        "sw.js",
        media_type="application/javascript",
        cache_control="no-cache",
        extra_headers={"Service-Worker-Allowed": "/"},
    )
